### ISSUE TITLE
encrypted passwords from dictionary

### ISSUE THREAD

**Issue by robotsdancing** [robotsdancing/Lab2#1]
in the line(44 currently) that says  " hashedPasswordList.add((md5Hash.digest(passwordList.get(i).getBytes())).toString());" it does not create a string of the hashed password like I expected, but I'll work on this some tomorrow to hopefully resolve the issue.

**Comment by Faore** [comment]
I've got you covered. Cleaned up the code a bit and got that working. You have to do some funny stuff to convert it into the md5 format. I found a working dictionary, but its huge. So I'll see if I can find a smaller one. If not, oh well it works fine.
